// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntmbesckstvkpepuxmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bWJlc2Nrc3R2a3BlcHV4bXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTQ5OTEsImV4cCI6MjA1OTc5MDk5MX0.WyL7BtBX27M7B9WDjc5qM4vhCa1OOZEQjuv74w8rJrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);